name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          
          plugin_introduction: yes
          
          plugin_habits: yes
          plugin_habits_days: 30
          config_timezone: America/Sao_Paulo

          plugin_notable: yes
          plugin_notable_filter: stars:>100
          plugin_notable_from: all

          plugin_followup: yes
          plugin_followup_sections: user
