name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          
          plugin_introduction: yes
          
          plugin_code: yes
          plugin_code_lines: 12 
          plugin_code_load: 100
          plugin_code_visibility: public
          
#           plugin_habits: yes
#           plugin_habits_days: 30
#           config_timezone: America/Sao_Paulo

          plugin_languages: yes

          plugin_notable: yes
          plugin_notable_filter: stars:>100
          plugin_notable_from: all

          plugin_followup: yes
          plugin_followup_sections: user
