name: "Run tests"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
      - run: npm ci
      - run: npm run test
